name: Rust Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"  # Runs on versioned tags like v1.0.0
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    name: Set Matrix Targets
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.set_targets.outputs.targets }}  # Make outputs available for subsequent jobs
    steps:
      - name: Set Matrix Targets
        id: set_targets
        # Target order
        # 0 - Linux
        # 1 - Apple X64
        # 2 - Apple aarch64/ARM
        # 3 - Windows
        run: |
          echo "targets=[\"x86_64-unknown-linux-gnu\",\"x86_64-apple-darwin\",\"aarch64-apple-darwin\",\"x86_64-pc-windows-msvc\"]" >> $GITHUB_OUTPUT

  test:
    name: Test for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        include: 
          - os: ubuntu-latest
            target: ${{ fromJson(needs.setup.outputs.targets)[0] }}
          - os: macos-latest
            target: ${{ fromJson(needs.setup.outputs.targets)[1] }}
          - os: macos-latest
            target: ${{ fromJson(needs.setup.outputs.targets)[2] }}
          - os: windows-latest
            target: ${{ fromJson(needs.setup.outputs.targets)[3] }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run check
        run: |
          echo "Running check for ${{ matrix.target }} on ${{ matrix.os }}"
          cargo check

  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    needs: setup

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: ${{ fromJson(needs.setup.outputs.targets)[0] }}
            ext: ""
            a_ext: ".tar.gz"
          - os: macos-latest
            target: ${{ fromJson(needs.setup.outputs.targets)[1] }}
            ext: ""
            a_ext: ".tar.gz"
          - os: macos-latest
            target: ${{ fromJson(needs.setup.outputs.targets)[2] }}
            ext: ""
            a_ext: ".tar.gz"
          - os: windows-latest
            target: ${{ fromJson(needs.setup.outputs.targets)[3] }}
            ext: ".exe"
            a_ext: ".zip"


    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Install Dependencies (Linux)
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt update && sudo apt install -y musl-tools gcc-aarch64-linux-gnu

      - name: Install UPX
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: sudo apt install -y upx

      - name: Install Rust Target
        run: rustup target add ${{ matrix.target }}
        

      - name: Build Application
        run: cargo build --release --target=${{ matrix.target }}

      - name: Rename Executable
        run: mv target/${{ matrix.target }}/release/timekeeper${{ matrix.ext }} timekeeper-${{ matrix.target }}${{ matrix.ext }}
      
      # Don't pack the windows executables AV will flag them
      # Don't pack for macos, bad support
      - name: Compress Executable with UPX
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          upx --best --lzma timekeeper-${{ matrix.target }}${{ matrix.ext }}

      - name: Archive Files (Windows)
        if: ${{ contains(matrix.os, 'windows') }}
        shell: pwsh
        run: |
          Compress-Archive -Path timekeeper-${{ matrix.target }}${{ matrix.ext }} -DestinationPath timekeeper-${{ matrix.target }}${{ matrix.a_ext }}

      - name: Archive Files (Linux/macOS)
        if: ${{ !contains(matrix.os, 'windows') }}
        run: |
          tar -czvf timekeeper-${{ matrix.target }}${{ matrix.a_ext }} timekeeper-${{ matrix.target }}${{ matrix.ext }}

      - name: Upload Archived Artifact
        uses: actions/upload-artifact@v4
        with:
          name: timekeeper-${{ matrix.target }}${{ matrix.a_ext }}
          path: |
            timekeeper-${{ matrix.target }}.zip
            timekeeper-${{ matrix.target }}.tar.gz

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v5
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TIMEKEEPER }}  # Use the PAT instead of GITHUB_TOKEN
          tag_name: ${{ github.ref_name }}
          files: artifacts/**
